ccflags-y = -Iinclude/rtos

obj-$(CONFIG_MEM_SELECT_1) = heap_1.o
obj-$(CONFIG_MEM_SELECT_2) = heap_2.o
obj-$(CONFIG_MEM_SELECT_3) = heap_3.o
obj-$(CONFIG_MEM_SELECT_4) = heap_4.o
obj-$(CONFIG_MEM_SELECT_5) = heap_5.o
